project_id = "hguzgggcdnerycccihov"

[functions.send-activation-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-trial-emails]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.contact-form]
verify_jwt = false
