/**
 * Broken Related Resources / in-body blog slugs → registered allBlogs slugs.
 * Used by BlogSlugRedirect so old hrefs stop 404ing without editing post HTML.
 */
export const BLOG_SLUG_REDIRECTS: Record<string, string> = {
  'initial-access-brokers-dark-web-monitoring':
    'initial-access-brokers-how-dark-web-monitoring-exposes-them',
  'what-is-dark-web-monitoring-how-it-works-2025':
    'what-is-dark-web-monitoring-and-how-does-it-actually-work-in-2026',
  'stealer-logs-dark-web-monitoring-connection':
    'stealer-logs-and-dark-web-monitoring-the-connection-explained',
  'what-is-credential-leak-detection':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'what-is-data-leak-detection':
    'what-is-data-leak-detection-and-how-is-it-different-from-dlp',
  'ransomware-groups-leak-sites-double-extortion':
    'double-extortion-ransomware-monitoring-leak-sites-for-your-data',
  'data-leak-detection-vs-dlp':
    'what-is-data-leak-detection-and-how-is-it-different-from-dlp',
  'removed-vs-suppressed-dark-web-data':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'real-time-dark-web-monitoring-what-it-means':
    'real-time-dark-web-monitoring-what-it-means-and-why-it-matters',
  'leaked-credentials-initial-access-mitre-attack':
    'leaked-credentials-as-initial-access-mitre-attck-coverage',
  'dark-web-data-removal-what-is-possible-2026':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'infostealer-logs-explained':
    'infostealer-logs-what-they-contain-and-why-you-need-to-monitor-them',
  'dark-web-data-removal-verification-methods':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'stealer-malware-credential-theft-detection':
    'stealer-malware-and-credential-theft-detection-and-response-guide',
  'dark-web-monitoring-vs-siem-key-differences':
    'dark-web-monitoring-vs-siem-key-differences-security-teams-must-know',
  'monitoring-ransomware-leak-sites-guide':
    'monitoring-ransomware-leak-sites-a-security-teams-guide',
  'credential-leak-detection-siem-integration':
    'credential-leak-detection-integrating-with-your-siem-platform',
  'dark-web-data-removal-after-ransomware-attack':
    'ransomware-negotiation-what-happens-on-the-dark-web-after-an-attack',
  'dark-web-data-removal-incident-response':
    'dark-web-intelligence-for-incident-response-practical-guide',
  'dark-web-data-removal-success-rate':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'credential-stuffing-attacks-dark-web-stolen-passwords':
    'how-credential-stuffing-attacks-use-dark-web-stolen-passwords',
  'roi-dark-web-monitoring-ciso-board':
    'the-roi-of-dark-web-monitoring-what-cisos-need-to-tell-the-board',
  'dark-web-monitoring-detects-threats-before-hackers-strike':
    'how-dark-web-monitoring-detects-threats-before-hackers-strike',
  'pii-data-leak-detection-gdpr-requirements':
    'pii-data-leak-detection-what-gdpr-requires-you-to-monitor',
  'dark-web-monitoring-catches-ransomware-before-deployment':
    'how-dark-web-monitoring-catches-ransomware-before-deployment',
  'how-credential-leaks-lead-to-ransomware':
    'how-credential-leaks-lead-to-ransomware-the-attack-chain-explained',
  'combo-lists-explained-monitoring':
    'combo-lists-explained-what-they-are-and-how-to-monitor-for-them',
  'data-leak-detection-roi-prevention-vs-breach-cost':
    'data-leak-detection-roi-quantifying-prevention-vs-breach-cost',
  'dark-web-monitoring-soc-2-compensating-control':
    'dark-web-monitoring-as-a-soc-2-compensating-control',
  'dark-web-data-removal-vs-monitoring':
    'how-dark-web-monitoring-helps-prevent-data-leaks',
  'how-hackers-use-leaked-credentials-attack-paths':
    'how-hackers-use-leaked-credentials-7-attack-paths-to-block',
  'double-extortion-ransomware-leak-site-monitoring':
    'double-extortion-ransomware-monitoring-leak-sites-for-your-data',
  'detect-data-leak-before-customers-find-out':
    'how-to-detect-a-data-leak-before-your-customers-find-out',
  'how-ai-is-transforming-dark-web-monitoring-2025':
    'how-ai-is-transforming-dark-web-monitoring-in-2026',
  'dark-web-data-removal-gdpr-right-to-erasure':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'data-leak-detection-coverage-map-2025':
    'data-leak-detection-coverage-map-what-platforms-monitor-in-2026',
  'credential-leak-detection-vs-password-management':
    'credential-leak-detection-vs-password-management-critical-differences',
  'dark-web-monitoring-hipaa-compliance':
    'dark-web-monitoring-for-hipaa-compliance-what-healthcare-it-needs',
  'complete-dark-web-data-removal-checklist':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'credential-leak-detection-roi-business-value':
    'credential-leak-detection-roi-calculating-the-business-value',
  'employee-credential-leaks-detect-respond-2025':
    'employee-credential-leaks-how-to-detect-and-respond-in-2026',
  'dark-web-data-removal-roi-business-case':
    'how-to-calculate-the-roi-of-dark-web-monitoring-for-your-business',
  'breach-vs-leak-difference':
    'breach-vs-leak-understanding-the-critical-difference-for-security-teams',
  'data-leak-detection-vs-osint':
    'how-dark-web-data-leak-detection-differs-from-osint',
  'how-to-prioritize-dark-web-data-removal':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'internal-data-leaks-dark-web-attack-path':
    'how-internal-data-leaks-get-to-the-dark-web-attack-path-analysis',
  'dark-web-monitoring-for-financial-services':
    'dark-web-threat-intelligence-for-financial-services-ciso-teams',
  'hipaa-dark-web-monitoring-requirements':
    'dark-web-monitoring-for-hipaa-compliance-what-healthcare-it-needs',
  'credential-leak-detection-banking':
    'dark-web-credential-leaks-at-banks-2024-2025-case-studies',
  'dark-web-data-removal-how-it-works':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'how-ehr-credentials-end-up-dark-web-markets':
    'hospital-and-clinic-data-on-the-dark-web-what-gets-exposed',
  'phi-dark-web-markets-detection-timeline':
    'healthcare-data-leaks-phi-detection-and-breach-notification',
  'dark-web-monitoring-for-financial-institutions':
    'ftc-safeguards-rule-and-dark-web-monitoring-for-financial-institutions',
  'dark-web-monitoring-hospital-networks-after-ransomware':
    'how-dark-web-monitoring-catches-ransomware-before-deployment',
  'data-leak-detection-coverate-map-2025':
    'data-leak-detection-coverage-map-what-platforms-monitor-in-2026',
  'data-leak-detection-financial-services':
    'financial-data-leaks-how-banks-detect-and-contain-them',
  'api-security-and-threat-intelligence':
    'what-is-a-threat-intelligence-platform-tip-and-does-your-business-need-one',
  'credential-leak-detection':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'credential-leak-detection-competitive-intelligence':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'credential-leak-detection-compliance':
    'credential-leak-detection-in-regulated-industries-compliance-map',
  'credential-leak-detection-essentials':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'credential-leak-detection-for-banks-and-fintechs':
    'credential-leak-detection-for-financial-services-regulatory-view',
  'credential-leak-detection-for-financial-services':
    'credential-leak-detection-for-financial-services-regulatory-view',
  'credential-leak-detection-for-payment-gateways':
    'how-payment-processors-monitor-dark-web-for-stolen-card-data',
  'credential-leak-detection-for-remote-workforce':
    'credential-leak-detection-for-remote-and-hybrid-workforces',
  'credential-leak-detection-guide':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'credential-leak-detection-how-it-works':
    'what-is-credential-leak-detection-and-why-every-business-needs-it',
  'credential-leak-detection-pci-dss':
    'pci-dss-40-and-dark-web-monitoring-what-payment-processors-need-to-know',
  'credential-leak-detection-selfm-ideation':
    'credential-leak-detection-integrating-with-your-siem-platform',
  'credential-leak-detection-voi-business-value':
    'credential-leak-detection-roi-calculating-the-business-value',
  'credential-monitoring-financial-services':
    'credential-leak-detection-for-financial-services-regulatory-view',
  'dark-web-credential-leak-detection':
    'why-you-need-dark-web-monitoring-for-credential-leak-detection',
  'dark-web-credential-leak-detection-banking':
    'dark-web-credential-leaks-at-banks-2024-2025-case-studies',
  'dark-web-credential-leak-monitoring-for-financial-services':
    'credential-leak-detection-for-financial-services-regulatory-view',
  'dark-web-credential-leaks-banks-case-studies':
    'dark-web-credential-leaks-at-banks-2024-2025-case-studies',
  'dark-web-intelligence-aml-compliance':
    'dark-web-intelligence-for-banking-aml-and-fraud-teams',
  'dark-web-monitoring-essential-guide':
    'what-is-dark-web-monitoring-and-how-does-it-work',
  'dark-web-monitoring-financial-services':
    'dark-web-threat-intelligence-for-financial-services-ciso-teams',
  'dark-web-monitoring-for-community-banks':
    'dark-web-monitoring-for-community-banks-with-limited-security-staff',
  'dark-web-monitoring-for-credential-leak-detection':
    'why-you-need-dark-web-monitoring-for-credential-leak-detection',
  'dark-web-monitoring-for-healthcare':
    'dark-web-monitoring-for-canadian-healthcare-organizations',
  'dark-web-monitoring-for-saas-companies':
    'saas-company-data-on-the-dark-web-whats-at-risk-and-how-to-monitor',
  'dark-web-threat-intelligence-for-uk-banks':
    'dark-web-threats-targeting-london-financial-institutions',
  'dark-web-threats-financial-sector-2024':
    'dark-web-threats-facing-the-banking-sector-in-2025',
  'dark-web-threats-for-alternative-asset-managers':
    'dark-web-threat-intelligence-for-financial-services-ciso-teams',
  'data-leak-detection-2025':
    'data-leak-detection-coverage-map-what-platforms-monitor-in-2026',
  'data-leak-detection-and-financial-compliance':
    'credential-leak-detection-for-financial-services-regulatory-view',
  'data-leak-detection-and-prevention':
    'data-leak-detection-vs-data-loss-prevention-which-does-what',
  'data-leak-detection-and-response-for-retail':
    'data-leak-detection-for-retail-loyalty-program-databases',
  'data-leak-detection-approaches':
    'what-is-data-leak-detection-and-how-is-it-different-from-dlp',
  'data-leak-detection-enterprise':
    'what-is-data-leak-detection-and-how-is-it-different-from-dlp',
  'data-leak-detection-for-pci-compliance':
    'pci-dss-40-compliance-and-dark-web-monitoring-what-finance-teams-need',
  'data-leak-detection-for-regulated-crypto-platforms':
    'data-leak-detection-for-cryptocurrency-exchanges',
  'data-leak-detection-in-third-party-vendors':
    'data-leak-detection-after-a-third-party-vendor-breach',
  'data-leak-detection-industry':
    'data-leak-detection-for-the-hospitality-and-travel-industry',
  'data-leak-detection-pci':
    'pci-dss-40-and-dark-web-monitoring-new-requirements-explained',
  'data-leak-detection-supply-chain':
    'data-leak-detection-for-supply-chain-partners',
  'data-leak-detection-vendor-risk':
    'data-leak-detection-questions-to-ask-every-vendor',
  'data-leak-monitoring-in-financial-services':
    'financial-data-leaks-how-banks-detect-and-contain-them',
  'data-leak-monitoring-occ-guidance':
    'financial-regulator-dark-web-guidance-occ-fdic-and-fed-requirements',
  'ffiec-threat-intelligence-guidance-and-dark-web-monitoring':
    'dark-web-monitoring-threat-intelligence',
  'financial-services-dark-web-threat-landscape-2025':
    'dark-web-threat-intelligence-for-financial-services-ciso-teams',
  'glba-safeguards-rule-dark-web-monitoring':
    'glba-safeguards-rule-dark-web-monitoring-as-a-required-control',
  'healthcare-ransomware-groups-dark-web-threat-intelligence':
    'hospital-and-clinic-data-on-the-dark-web-what-gets-exposed',
  'initial-access-brokers-and-the-financial-sector':
    'initial-access-brokers-how-dark-web-monitoring-exposes-them',
  'ransomware-leak-sites-targeting-financial-institutions':
    'monitoring-ransomware-leak-sites-a-security-teams-guide',
  'threat-intelligence-platform-financial-services':
    'dark-web-threat-intelligence-for-financial-services-ciso-teams',

  // Bug #8 — ghost "vs" sitemap slugs (on disk / sitemap, not in allBlogs)
  'darkthreat-vs-darkowl-head-to-head-comparison-2025':
    'darkthreat-vs-darkowl-head-to-head-comparison-2026',
  'enterprise-vs-smb-dark-web-monitoring-feature-comparison-2025':
    'enterprise-vs-smb-dark-web-monitoring-feature-comparison-2026',
  'dark-web-data-removal-vs-monitoring-why-you-need-both':
    'how-dark-web-monitoring-helps-prevent-data-leaks',
  'dark-web-data-removal-vs-data-recovery-understanding-the-difference':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'dark-web-data-removal-vs-devaluing-stolen-data-which-strategy-works':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'dark-web-data-removal-vs-suppress-different-outcomes-explained':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'proactive-vs-reactive-dark-web-data-removal-strategy-guide':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'removed-vs-suppressed-dark-web-data-difference-and-risk':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
  'dark-web-data-removal-service-vs-diy-cost-and-risk-analysis':
    'can-you-remove-data-from-the-dark-web-after-monitoring-finds-it',
};
