// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hguzgggcdnerycccihov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndXpnZ2djZG5lcnljY2NpaG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTQxODksImV4cCI6MjA3MTY5MDE4OX0.hcBRIiYV8LLkMnh1SQM9y4IrjZkCkHZ5KgTDlLeV1PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});